### ISSUE TITLE
550 The system cannot find the file specified

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-data-3gpp#6]
```
Started at: 2024-01-03 10:40:08 +0000
/home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:483:in `getresp': 550 The system cannot find the file specified.  (Net::FTPPermError)
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:495:in `voidresp'
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:518:in `block in voidcmd'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:516:in `voidcmd'
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:1182:in `chdir'
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/bundler/gems/relaton-3gpp-7ffd21554b2a/lib/relaton_3gpp/data_fetcher.rb:89:in `get_file'
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/bundler/gems/relaton-3gpp-7ffd21554b2a/lib/relaton_3gpp/data_fetcher.rb:49:in `fetch'
	from /home/runner/work/relaton-data-3gpp/relaton-data-3gpp/vendor/bundle/ruby/3.1.0/bundler/gems/relaton-3gpp-7ffd21554b2a/lib/relaton_3gpp/data_fetcher.rb:37:in `fetch'
	from crawler.rb:9:in `<main>'
```

Full log: https://github.com/relaton/relaton-data-3gpp/actions/runs/7396260902/job/20121028059#step:7:61

**Comment by ronaldtse** [comment]
The database file has been deprecated. 

3GPP has provided us with a new mechanism to create bibliographic items. 

This will depend on @andrew2net to update the fetch mechanism.

**Comment by andrew2net** [comment]
> 3GPP has provided us with a new mechanism to create bibliographic items.

@ronaldtse where can I find information about that new mechanism?

**Comment by ronaldtse** [comment]
@andrew2net I have given the information to you privately.

**Comment by andrew2net** [comment]
Fixed in relaton-3gpp v2.1.3
